services:
  fastapi:
    container_name: fastapi
    build: ..
    command: poetry run uvicorn src.interfaces.web.main:create_app --factory --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ..:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge