# services:
#   postgres:
#     image: postgres:17
#     container_name: postgres_db
#     restart: always
    # environment:
      # - POSTGRES_DB=${DATABASE_NAME}
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - backend

# volumes:
#   pgdata:

# networks:
#   backend:
#     driver: bridge



version: "3.9"

services:
  postgres_db:
    image: postgres:17
    container_name: postgres_db
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: toor
      # POSTGRES_DB: tempotrack
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    
volumes:
  pgdata:

networks:
  backend:
    driver: bridge