"""empty message

Revision ID: 4683aa496bcf
Revises: 22ee9fe5c724
Create Date: 2026-01-09 12:03:50.188128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4683aa496bcf'
down_revision: Union[str, Sequence[str], None] = '22ee9fe5c724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.Column('time_start', postgresql.TIME(), nullable=False),
    sa.Column('time_end', postgresql.TIME(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'CANCELED', name='schedule_notification_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_notifications_id'), 'schedule_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_notifications_schedule_item_id'), 'schedule_notifications', ['schedule_item_id'], unique=False)
    op.create_index(op.f('ix_schedule_notifications_user_id'), 'schedule_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_notifications_user_id'), table_name='schedule_notifications')
    op.drop_index(op.f('ix_schedule_notifications_schedule_item_id'), table_name='schedule_notifications')
    op.drop_index(op.f('ix_schedule_notifications_id'), table_name='schedule_notifications')
    op.drop_table('schedule_notifications')
    # ### end Alembic commands ###
